### ISSUE TITLE
Linux 

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1047]
Error reported in course CS101JAVAAP on page any by user adegenn degennaro@gssm.k12.sc.us
I have tried a number of times to get the code windows to run code in my browers. I have tried firefox and chromium but both fail.  If I press it too far I get an error on code that should work fine.  

FYI I am also running a class in python and using the same browsers there without any problem.  Seems just the CSAwesome pages are giving me problems. Is there a fix?

**Comment by bhoffman0** [comment]
Could you please send a screenshot or two of what's not working and if there are any error messages? CSAwesome Java active codes do work on Chrome and Firefox. There's 1 known error in 1.3 Activity 16 CaseSensitiveClass, but we have no error reports on others.

**Comment by adegenn** [comment]
Code segments fail to execute completely, it just hangs. For example:
![image](https://user-images.githubusercontent.com/69872109/90559809-2c0d2d00-e16c-11ea-8c63-8963ab908881.png)



Another example, in jGrasp I have:

![image](https://user-images.githubusercontent.com/69872109/90559651-e51f3780-e16b-11ea-9159-d8901506b342.png)

Here is what I get when I try online:

![image](https://user-images.githubusercontent.com/69872109/90563129-557c8780-e171-11ea-9ac9-19b461675f75.png)

It fails the same way whether I use firefox or chromium.

**Comment by bhoffman0** [comment]
Thank you for these examples! I was able to replicate Activity 3, although Activity 2 does work for me. Do any of the active code windows work for you? What happens if you change the code slightly and run again? Activity 3 works for me if I change it slightly.  What happens if you copy the code into the Scratch area (pencil icon at the top)? Does that work? 

These were working fine until recently. I think we're having problems with the autograding code that we added. We'll try to fix it by trying different things in the next few days. Sorry about this!
-Beryl

**Comment by bhoffman0** [comment]
We think we have fixed this problem. Could you please try again and let us know? You may have to do a hard refresh CTRL F5.

**Comment by adegenn** [comment]
OK,
                 **still not working in my Firefox, Chromium,** 

       BUT it does work in BRAVE, a browser I recently downloaded for another application.  (Tell me if I am misled :-D)

However, perhaps that is a clue?  My Firefox and Chromium are old(er)?  Brave is new.

![image](https://user-images.githubusercontent.com/69872109/90637098-8c967b80-e1f9-11ea-885f-919ce19631ec.png)

![image](https://user-images.githubusercontent.com/69872109/90637148-9ddf8800-e1f9-11ea-957c-749b24deb97e.png)

and the other:
![image](https://user-images.githubusercontent.com/69872109/90637229-bbaced00-e1f9-11ea-9f85-b8cd17754cdb.png)

**Comment by irunestone** [comment]
Not just old VERY old Ubuntu 14.04 means 2014 that is 3 LTS releases out of date.   Current Firefox is version 79 and current Chrome is 84

I wouldn't even know where to begin to figure out what is going on in a browser that old.  Things have evolved a lot in just the past 2 years.

Brad

Brad Miller, PhD
Founder, Runestone Interactive, LLC
Professor Emeritus, Luther College
Blog: http://reputablejournal.com

**Comment by adegenn** [comment]
Dr Miller,

Thanks for the update!

Regards,
Al

PS By the way do you know anything about the Brave browser?  Since it works, I will use it for this task as well.
***************************************************************************************************************************
Alfred DeGennaro, DBA
Computer Science Instructor
Chair of Computer, Business, & Engineering

South Carolina Governor's School for Science and Mathematics

401 Railroad Avenue

Hartsville, South Carolina 29550

T: 843-383-3901<tel:843-383-3901>

F: 843-383-3903

degennaro@gssm.k12.sc.us


============================================================================
This message may contain information confidential to the South Carolina Governor’s School for Science and Mathematics (GSSM) and is intended only for the recipient(s) named. If you are not a named recipient, you should not disseminate, distribute, or copy this email or any attachments. Notify sender immediately if you received this email by mistake and fully delete this email, and any attachments. GSSM accepts no responsibility for errors or omissions in this message arising from email transmission. Recipients are advised to take appropriate steps to ensure the safety of any attachments or links prior to accessing them.

________________________________
